name: Build and Deploy Quarto Book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Render HTML
        run: quarto render index.qmd --to html

      - name: Render PDF
        run: quarto render index.qmd --to pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Open-Geoinformatics-PDF
          path: docs/*.pdf

      - name: Deploy HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_book_html
          user_name: "GitHub Actions"
          user_email: "actions@github.com"
