name: Publish Quarto Book

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup LaTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: Render HTML
        run: quarto render . --to html

      - name: Render PDF
        run: quarto render . --to pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: _book/*.pdf

      - name: Deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
